#!/bin/bash
# A convenience script that runs a Nagios service check and sends the output
# through send_nsca.
# usage: nsca_check <service_name> <command>
service=$1
shift
case $* in
  /*)
    output=`$*`
  ;;
  *)
    output=`/opt/nagios/libexec/$*`
  ;;
esac
exitcode=$?
hostname=`hostname | sed 's/\..*//'`
server=`grep server_address /opt/nagios/etc/nsca.cfg |sed 's/.*=//'`
if test -z "$server"; then
  server=$hostname
fi
/usr/bin/printf "%s\t%s\t%s\t%s\n" \
                "$hostname" "$service" "$exitcode" "$output" | \
  /opt/nagios/bin/send_nsca -to 120 -H $server -c /opt/nagios/etc/send_nsca.cfg
